use_frameworks!

platform :ios, '10.0'

target 'YDProgressHUD_Example' do
  pod 'YDSVProgressHUD', :path => '../'
  
  
  # 添加以下配置来解决 ARC 相关问题
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
        config.build_settings['CLANG_ENABLE_OBJC_ARC'] = 'YES'
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] = ['$(inherited)', '$(SDKROOT)/System/Library/Frameworks']
      end
    end
  end

  target 'YDProgressHUD_Tests' do
    inherit! :search_paths
    pod 'FBSnapshotTestCase'
  end
end
