use_frameworks!

platform :ios, '10.0'

target 'YDProgressHUD_Example' do
  pod 'YDProgressHUD', :path => '../'

  target 'YDProgressHUD_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
