use_frameworks!

platform :ios, '10.0'

target 'YDProgressHUD_Example' do
  pod 'YDSVProgressHUD', :path => '../'
  
  
  # 添加以下配置来解决 ARC 相关问题
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        # 禁用 ARC 弱引用兼容（解决 libarclite 错误）
        config.build_settings['CLANG_ENABLE_OBJC_ARC_WEAK'] = 'NO'
        # 修复 Swift 编译警告
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone' if config.name == 'Debug'
        config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
        config.build_settings['CLANG_ENABLE_OBJC_ARC'] = 'YES'
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] = ['$(inherited)', '$(SDKROOT)/System/Library/Frameworks']
      end
    end
  end
  
  target 'YDProgressHUD_Tests' do
    inherit! :search_paths
    pod 'FBSnapshotTestCase'
  end
end
